/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Graficos.TableroGrafico;
import Presentacion.IPresentacionJuego;
import dominio_domino.Ficha;
import dominio_domino.FichaJugador;
import dominio_domino.FichaPozo;
import dominio_domino.FichaTablero;
import dominio_domino.Jugador;
import dominio_domino.Pozo;
import dominio_dominodto.JugadorDTO;
import java.awt.Color;
import java.awt.Image;
import java.awt.Insets;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class VistaJuego extends javax.swing.JFrame  {

    private IPresentacionJuego presentador;
    private TableroGrafico tablero;

    /**
     * Creates new form VistaJuego
     */
    public VistaJuego(IPresentacionJuego presentador) {
        this.presentador = presentador;
        tablero = new TableroGrafico();
        initComponents();
        btnRobar.setVisible(false);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jugador1 = new javax.swing.JPanel();
        lblJugador1 = new javax.swing.JLabel();
        lblAvatar1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Jugador2 = new javax.swing.JPanel();
        lblJugador2 = new javax.swing.JLabel();
        lblAvatar2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Jugador3 = new javax.swing.JPanel();
        lblJugador3 = new javax.swing.JLabel();
        lblAvatar3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Jugador4 = new javax.swing.JPanel();
        lblJugador4 = new javax.swing.JLabel();
        lblAvatar4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnRobar = new javax.swing.JButton();
        pantallaespera = new javax.swing.JPanel();
        Jugador5 = new javax.swing.JPanel();
        lblJugador5 = new javax.swing.JLabel();
        lblAvatar5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        Jugador6 = new javax.swing.JPanel();
        lblJugador6 = new javax.swing.JLabel();
        lblAvatar6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        Jugador7 = new javax.swing.JPanel();
        lblJugador7 = new javax.swing.JLabel();
        lblAvatar7 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        Jugador8 = new javax.swing.JPanel();
        lblJugador8 = new javax.swing.JLabel();
        lblAvatar8 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnRobar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 0));
        setMinimumSize(new java.awt.Dimension(1300, 600));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        Jugador1.setBackground(new java.awt.Color(204, 204, 204));
        Jugador1.setPreferredSize(new java.awt.Dimension(500, 130));
        Jugador1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugador1.setText("Jugador:");
        Jugador1.add(lblJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 44, -1, -1));
        Jugador1.add(lblAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Jugador1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 0, 50, 130));

        Jugador2.setBackground(new java.awt.Color(204, 204, 204));
        Jugador2.setPreferredSize(new java.awt.Dimension(500, 130));
        Jugador2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugador2.setText("Jugador:");
        Jugador2.add(lblJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 44, -1, -1));
        Jugador2.add(lblAvatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Jugador2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 50, 130));

        Jugador3.setBackground(new java.awt.Color(204, 204, 204));
        Jugador3.setPreferredSize(new java.awt.Dimension(500, 130));
        Jugador3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugador3.setText("Jugador:");
        Jugador3.add(lblJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 44, -1, -1));
        Jugador3.add(lblAvatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Jugador3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 0, 50, 130));

        Jugador4.setBackground(new java.awt.Color(204, 204, 204));
        Jugador4.setPreferredSize(new java.awt.Dimension(500, 130));
        Jugador4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugador4.setText("Jugador:");
        Jugador4.add(lblJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 44, -1, -1));
        Jugador4.add(lblAvatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Jugador4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 50, 130));

        jButton1.setText("Iniciar Votacion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnRobar.setText("Robar Ficha");
        btnRobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRobarActionPerformed(evt);
            }
        });

        pantallaespera.setBackground(new java.awt.Color(0, 153, 0));
        pantallaespera.setForeground(new java.awt.Color(0, 153, 0));

        Jugador5.setBackground(new java.awt.Color(204, 204, 204));
        Jugador5.setPreferredSize(new java.awt.Dimension(500, 130));
        Jugador5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugador5.setText("Jugador:");
        Jugador5.add(lblJugador5, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 44, -1, -1));
        Jugador5.add(lblAvatar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Jugador5.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 0, 50, 130));

        Jugador6.setBackground(new java.awt.Color(204, 204, 204));
        Jugador6.setPreferredSize(new java.awt.Dimension(500, 130));
        Jugador6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugador6.setText("Jugador:");
        Jugador6.add(lblJugador6, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 44, -1, -1));
        Jugador6.add(lblAvatar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Jugador6.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 50, 130));

        Jugador7.setBackground(new java.awt.Color(204, 204, 204));
        Jugador7.setPreferredSize(new java.awt.Dimension(500, 130));
        Jugador7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugador7.setText("Jugador:");
        Jugador7.add(lblJugador7, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 44, -1, -1));
        Jugador7.add(lblAvatar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Jugador7.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 0, 50, 130));

        Jugador8.setBackground(new java.awt.Color(204, 204, 204));
        Jugador8.setPreferredSize(new java.awt.Dimension(500, 130));
        Jugador8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugador8.setText("Jugador:");
        Jugador8.add(lblJugador8, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 44, -1, -1));
        Jugador8.add(lblAvatar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Jugador8.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 50, 130));

        jButton3.setText("Iniciar Votacion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnRobar1.setText("Robar Ficha");
        btnRobar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRobar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pantallaesperaLayout = new javax.swing.GroupLayout(pantallaespera);
        pantallaespera.setLayout(pantallaesperaLayout);
        pantallaesperaLayout.setHorizontalGroup(
            pantallaesperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaesperaLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(pantallaesperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pantallaesperaLayout.createSequentialGroup()
                        .addComponent(Jugador5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pantallaesperaLayout.createSequentialGroup()
                        .addComponent(Jugador6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(243, 243, 243)
                        .addComponent(btnRobar1))
                    .addComponent(Jugador7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jugador8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pantallaesperaLayout.setVerticalGroup(
            pantallaesperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaesperaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pantallaesperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jugador5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pantallaesperaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(pantallaesperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jugador6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pantallaesperaLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnRobar1)))
                .addGap(17, 17, 17)
                .addComponent(Jugador7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(Jugador8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(Jugador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(Jugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(807, 807, 807)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(812, 812, 812)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(830, 830, 830)
                        .addComponent(btnRobar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(Jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(Jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pantallaespera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(481, 481, 481)
                        .addComponent(Jugador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(Jugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(622, 622, 622)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(btnRobar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(Jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pantallaespera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        inicioVotacion();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

    }//GEN-LAST:event_formKeyReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        arrastrarFicha(evt);
    }//GEN-LAST:event_formMouseDragged

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased

        realizarMovimiento(evt);
    }//GEN-LAST:event_formMouseReleased

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        agarrarFicha(evt);
    }//GEN-LAST:event_formMousePressed

    private void btnRobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRobarActionPerformed
        robarFicha();
    }//GEN-LAST:event_btnRobarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnRobar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRobar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRobar1ActionPerformed

    public void mostrarJugadores() {
        List<JugadorDTO> list = presentador.listaJugadores();
        for (int i = 0; i < list.size(); i++) {
            if (i == 0) {
                lblJugador1.setText(list.get(0).getNombre());
                ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(list.get(0).getAvatar()));
                ImageIcon iconoRedimensionado = new ImageIcon(iconoOriginal.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH));
                lblAvatar1.setIcon(iconoRedimensionado);
            }
            if (i == 1) {
                lblJugador2.setText(list.get(1).getNombre());
                ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(list.get(1).getAvatar()));
                ImageIcon iconoRedimensionado = new ImageIcon(iconoOriginal.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH));
                lblAvatar2.setIcon(iconoRedimensionado);
            }
            if (i == 2) {
                lblJugador3.setText(list.get(2).getNombre());
                ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(list.get(2).getAvatar()));
                ImageIcon iconoRedimensionado = new ImageIcon(iconoOriginal.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH));
                lblAvatar3.setIcon(iconoRedimensionado);
            }
            if (i == 3) {
                lblJugador4.setText(list.get(3).getNombre());
                ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(list.get(3).getAvatar()));
                ImageIcon iconoRedimensionado = new ImageIcon(iconoOriginal.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH));
                lblAvatar4.setIcon(iconoRedimensionado);
            }
        }

    }

    public void pintarFichas() {
        tablero.repintarFichasJugador();
    }

    public void robarFicha() {
        if (!isTurno()) {
          
            return;
        }
        presentador.robarFicha();
    }

    public int validaHitbox(MouseEvent e) {
        return tablero.validaHitbox(e);
    }

    public void mostrarMensajeError(String error) {
        JOptionPane.showMessageDialog(rootPane, error);
    }

    public void agarrarFicha(MouseEvent evt) {
        if (!isTurno()) {
            return;
        }
        Insets insets = this.getInsets();
        int adjustedX = evt.getX() - insets.left;
        int adjustedY = evt.getY() - insets.top;
        tablero.moverFicha(new MouseEvent(evt.getComponent(), evt.getID(), evt.getWhen(), evt.getModifiersEx(), adjustedX, adjustedY, evt.getClickCount(), evt.isPopupTrigger()));

    }

    public void arrastrarFicha(MouseEvent evt) {
        if (!isTurno()) {
           
            return;
        }
        Insets insets = this.getInsets();
        int adjustedX = evt.getX() - insets.left;
        int adjustedY = evt.getY() - insets.top;
        tablero.arrastrarFicha(new MouseEvent(evt.getComponent(), evt.getID(), evt.getWhen(), evt.getModifiersEx(), adjustedX, adjustedY, evt.getClickCount(), evt.isPopupTrigger()));

    }

    public void realizarMovimiento(MouseEvent evt) {
        if (!isTurno()) {
          
            return;
        }
        Insets insets = this.getInsets();
        int adjustedX = evt.getX() - insets.left;
        int adjustedY = evt.getY() - insets.top;

        int valida = validaHitbox(new MouseEvent(evt.getComponent(), evt.getID(), evt.getWhen(), evt.getModifiersEx(), adjustedX, adjustedY, evt.getClickCount(), evt.isPopupTrigger()));
        if (valida == 0) {

            return;
        }
        FichaJugador ficha = tablero.obtenerFichaSeleccionada();
        FichaTablero f = new FichaTablero(ficha.getImagen(), ficha.getPuntoAbajo(), ficha.getPuntoArriba());
        boolean validaFicha = false;

        switch (valida) {
            case 1:
                validaFicha = presentador.realizaMovimiento(f, valida);
                break;
            case 2:
                validaFicha = presentador.realizaMovimiento(f, valida);
                break;
            case 3:
                validaFicha = presentador.realizaMovimiento(f, valida);
                break;
        }
        if (!validaFicha) {
            tablero.resetearFichaSeleccionada();
        }
        if (validaFicha) {
            switch (valida) {
                case 1:
                    tablero.colocarInicial(f);
                    break;
                case 2:
                    tablero.colocarTrenDerecha(f);
                    break;
                case 3:
                    tablero.colocarTrenIzquierda(f);
                    break;
            }
            presentador.eliminarFichaJugador(ficha);
        }
    }

    public void iniciarJuego() {
        Jugador1.setVisible(false);
        Jugador2.setVisible(false);
        Jugador3.setVisible(false);
        Jugador4.setVisible(false);
        add(tablero);
        presentador.iniciarPartida();
        this.setContentPane(tablero);
        tablero.add(btnRobar);
        btnRobar.setVisible(true);
        tablero.agregarFichasIniciales();
    }

    public void inicioVotacion() {
        int opcion = JOptionPane.showConfirmDialog(null, "¿Deseas continuar?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            iniciarJuego();
        } else {
            // El usuario hizo clic en "No" o cerró el cuadro de diálogo
            JOptionPane.showMessageDialog(null, "Operación cancelada.");
        }
    }

    public boolean isTurno() {
        return presentador.isTurno();
    }

    public void asignarJugadorJugando(Jugador jugador) {
        tablero.setJugador(jugador);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jugador1;
    private javax.swing.JPanel Jugador2;
    private javax.swing.JPanel Jugador3;
    private javax.swing.JPanel Jugador4;
    private javax.swing.JPanel Jugador5;
    private javax.swing.JPanel Jugador6;
    private javax.swing.JPanel Jugador7;
    private javax.swing.JPanel Jugador8;
    private javax.swing.JButton btnRobar;
    private javax.swing.JButton btnRobar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblAvatar1;
    private javax.swing.JLabel lblAvatar2;
    private javax.swing.JLabel lblAvatar3;
    private javax.swing.JLabel lblAvatar4;
    private javax.swing.JLabel lblAvatar5;
    private javax.swing.JLabel lblAvatar6;
    private javax.swing.JLabel lblAvatar7;
    private javax.swing.JLabel lblAvatar8;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JLabel lblJugador3;
    private javax.swing.JLabel lblJugador4;
    private javax.swing.JLabel lblJugador5;
    private javax.swing.JLabel lblJugador6;
    private javax.swing.JLabel lblJugador7;
    private javax.swing.JLabel lblJugador8;
    private javax.swing.JPanel pantallaespera;
    // End of variables declaration//GEN-END:variables

    
}
