/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Presentacion.IPresentadorUnirse;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author marcos
 */
public class VistaUnirse extends javax.swing.JFrame {

    private IPresentadorUnirse presentador;

    /**
     * Creates new form vistaUnirse
     */
    public VistaUnirse(IPresentadorUnirse presentador) {
        this.presentador = presentador;
        initComponents();
 
        avatar1.setIcon( new ImageIcon(getClass().getResource("/Avatares/avatar1.jpg")));
        avatar2.setIcon( new ImageIcon(getClass().getResource("/Avatares/avatar2.jpg")));
        avatar3.setIcon( new ImageIcon(getClass().getResource("/Avatares/avatar3.jpg")));
        avatar4.setIcon( new ImageIcon(getClass().getResource("/Avatares/avatar4.jpeg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        chbxAvatar1 = new javax.swing.JCheckBox();
        chbxAvatar2 = new javax.swing.JCheckBox();
        chbxAvatar3 = new javax.swing.JCheckBox();
        chbxAvatar4 = new javax.swing.JCheckBox();
        avatar4 = new javax.swing.JLabel();
        avatar1 = new javax.swing.JLabel();
        avatar2 = new javax.swing.JLabel();
        avatar3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Escoge tu avatar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 430, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre de jugador:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 191, -1));

        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 357, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Unirse a partida");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Volver a menu");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 20, -1, -1));

        buttonGroup1.add(chbxAvatar1);
        chbxAvatar1.setSelected(true);
        jPanel1.add(chbxAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, -1, -1));

        buttonGroup1.add(chbxAvatar2);
        jPanel1.add(chbxAvatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, -1, -1));

        buttonGroup1.add(chbxAvatar3);
        jPanel1.add(chbxAvatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, -1, -1));

        buttonGroup1.add(chbxAvatar4);
        jPanel1.add(chbxAvatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 450, -1, -1));

        avatar4.setPreferredSize(new java.awt.Dimension(308, 308));
        jPanel1.add(avatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 130, -1, -1));

        avatar1.setPreferredSize(new java.awt.Dimension(308, 308));
        jPanel1.add(avatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        avatar2.setPreferredSize(new java.awt.Dimension(308, 308));
        jPanel1.add(avatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        avatar3.setPreferredSize(new java.awt.Dimension(308, 308));
        jPanel1.add(avatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        crearJugador();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed
    public boolean validaJugador(){
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Nombre Vacio");
            return true;
        }
         return false;
    }
    public void crearJugador() {
        if (validaJugador()) {
            return;
        }
        String nombre = txtNombre.getText();
        String avatar = null;
        if (chbxAvatar1.isSelected()) {
            avatar = "/Avatares/avatar1.jpg";
        }
        if (chbxAvatar2.isSelected()) {
            avatar = "/Avatares/avatar2.jpg";
        }
        if (chbxAvatar3.isSelected()) {
            avatar = "/Avatares/avatar3.jpg";
        }
        if (chbxAvatar4.isSelected()) {
            avatar = "/Avatares/avatar4.jpeg";
        }
       
        presentador.crearJugador(nombre, avatar);
    }

    public void muestraMensajeError() {
        JOptionPane.showMessageDialog(rootPane, "Error", "ERROR", JOptionPane.ERROR_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatar1;
    private javax.swing.JLabel avatar2;
    private javax.swing.JLabel avatar3;
    private javax.swing.JLabel avatar4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chbxAvatar1;
    private javax.swing.JCheckBox chbxAvatar2;
    private javax.swing.JCheckBox chbxAvatar3;
    private javax.swing.JCheckBox chbxAvatar4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
