/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MVP.Vista;

import Grafico.TableroGrafico;
import MVP.Presentador.IPresentacionJuego;

import dominio_dominodto.FichaDTO;
import dominio_dominodto.FichaTableroDTO;
import dominio_dominodto.JugadorDTO;
import dominio_dominodto.PartidaDTO;
import java.awt.Color;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Rectangle;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class VistaJuego extends javax.swing.JFrame {

    private IPresentacionJuego presentador;

    private TableroGrafico tablero;
    private boolean respuesta;
    private boolean partidaIniciada = false;
     private boolean votar=false;

    /**
     * Creates new form VistaJuego
     */
    public VistaJuego(IPresentacionJuego presentador) {
       
        this.presentador = presentador;
        tablero = new TableroGrafico(this);
        initComponents();
        btnRobar.setVisible(false);
        Votacion.setVisible(false);
        btnTerminar.setVisible(false);
        btnPasarTurno.setVisible(false);
        pantallaPuntuaciones.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        pantallaespera = new javax.swing.JPanel();
        Votacion = new javax.swing.JPanel();
        BtnNo = new javax.swing.JButton();
        btnSi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRobar = new javax.swing.JButton();
        Jugador3 = new javax.swing.JPanel();
        lblJugador3 = new javax.swing.JLabel();
        lblAvatar3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Jugador2 = new javax.swing.JPanel();
        lblJugador2 = new javax.swing.JLabel();
        lblAvatar2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Jugador4 = new javax.swing.JPanel();
        lblJugador4 = new javax.swing.JLabel();
        lblAvatar4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        Jugador1 = new javax.swing.JPanel();
        lblJugador1 = new javax.swing.JLabel();
        lblAvatar1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnIniciarVotacion = new javax.swing.JButton();
        btnPasarTurno = new javax.swing.JButton();
        btnTerminar = new javax.swing.JButton();
        btnAbandonarPartida = new javax.swing.JButton();
        pantallaPuntuaciones = new javax.swing.JPanel();
        JugadorPuntacion3 = new javax.swing.JPanel();
        lblJugadorP3 = new javax.swing.JLabel();
        lblAvatarP3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lblPuntosP3 = new javax.swing.JLabel();
        JugadorPuntacion2 = new javax.swing.JPanel();
        lblJugadorP2 = new javax.swing.JLabel();
        lblAvatarP2 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        lblPuntosP2 = new javax.swing.JLabel();
        JugadorPuntacion4 = new javax.swing.JPanel();
        lblJugadorP4 = new javax.swing.JLabel();
        lblAvatarP4 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        lblPuntosP4 = new javax.swing.JLabel();
        JugadorPuntacion1 = new javax.swing.JPanel();
        lblJugadorP1 = new javax.swing.JLabel();
        lblAvatarP1 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        lblPuntosP1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblCoronitaBroce = new javax.swing.JLabel();
        lblCoronitaDorada = new javax.swing.JLabel();
        lblCoronitaPlateada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 0));
        setMinimumSize(new java.awt.Dimension(1300, 600));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        pantallaespera.setBackground(new java.awt.Color(0, 153, 0));
        pantallaespera.setForeground(new java.awt.Color(0, 153, 0));

        BtnNo.setText("No");
        BtnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNoActionPerformed(evt);
            }
        });

        btnSi.setText("Si");
        btnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("¿Quieres iniciar la partida?");

        javax.swing.GroupLayout VotacionLayout = new javax.swing.GroupLayout(Votacion);
        Votacion.setLayout(VotacionLayout);
        VotacionLayout.setHorizontalGroup(
            VotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VotacionLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(VotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(BtnNo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
            .addGroup(VotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(VotacionLayout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addComponent(btnSi, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(276, Short.MAX_VALUE)))
        );
        VotacionLayout.setVerticalGroup(
            VotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VotacionLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(BtnNo)
                .addGap(57, 57, 57))
            .addGroup(VotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VotacionLayout.createSequentialGroup()
                    .addContainerGap(149, Short.MAX_VALUE)
                    .addComponent(btnSi)
                    .addGap(58, 58, 58)))
        );

        btnRobar.setText("Robar Ficha");
        btnRobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRobarActionPerformed(evt);
            }
        });

        Jugador3.setBackground(new java.awt.Color(204, 204, 204));
        Jugador3.setPreferredSize(new java.awt.Dimension(500, 130));
        Jugador3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugador3.setText("Jugador:");
        Jugador3.add(lblJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 44, -1, -1));
        Jugador3.add(lblAvatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Jugador3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 0, 50, 130));

        Jugador2.setBackground(new java.awt.Color(204, 204, 204));
        Jugador2.setPreferredSize(new java.awt.Dimension(500, 130));
        Jugador2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugador2.setText("Jugador:");
        Jugador2.add(lblJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 44, -1, -1));
        Jugador2.add(lblAvatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Jugador2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 50, 130));

        Jugador4.setBackground(new java.awt.Color(204, 204, 204));
        Jugador4.setPreferredSize(new java.awt.Dimension(500, 130));
        Jugador4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugador4.setText("Jugador:");
        Jugador4.add(lblJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 44, -1, -1));
        Jugador4.add(lblAvatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Jugador4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 50, 130));

        Jugador1.setBackground(new java.awt.Color(204, 204, 204));
        Jugador1.setPreferredSize(new java.awt.Dimension(500, 130));
        Jugador1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugador1.setText("Jugador:");
        Jugador1.add(lblJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 44, -1, -1));
        Jugador1.add(lblAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Jugador1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 0, 50, 130));

        btnIniciarVotacion.setText("Iniciar Votacion");
        btnIniciarVotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarVotacionActionPerformed(evt);
            }
        });

        btnPasarTurno.setText("Pasar Turno");
        btnPasarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasarTurnoActionPerformed(evt);
            }
        });

        btnTerminar.setText("Iniciar Votacion Terminar Partida");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        btnAbandonarPartida.setText("Abandonar Partida");
        btnAbandonarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbandonarPartidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pantallaesperaLayout = new javax.swing.GroupLayout(pantallaespera);
        pantallaespera.setLayout(pantallaesperaLayout);
        pantallaesperaLayout.setHorizontalGroup(
            pantallaesperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaesperaLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(pantallaesperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pantallaesperaLayout.createSequentialGroup()
                        .addComponent(Jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210)
                        .addGroup(pantallaesperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnIniciarVotacion, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(btnAbandonarPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pantallaesperaLayout.createSequentialGroup()
                        .addGroup(pantallaesperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pantallaesperaLayout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(Votacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(pantallaesperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRobar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPasarTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTerminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(Jugador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pantallaesperaLayout.setVerticalGroup(
            pantallaesperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaesperaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pantallaesperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pantallaesperaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnIniciarVotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAbandonarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(pantallaesperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pantallaesperaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(pantallaesperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pantallaesperaLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(Jugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pantallaesperaLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(Votacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pantallaesperaLayout.createSequentialGroup()
                        .addComponent(btnRobar)
                        .addGap(31, 31, 31)
                        .addComponent(btnPasarTurno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTerminar)))
                .addGap(10, 10, 10)
                .addComponent(Jugador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pantallaPuntuaciones.setBackground(new java.awt.Color(0, 153, 0));
        pantallaPuntuaciones.setForeground(new java.awt.Color(0, 153, 0));

        JugadorPuntacion3.setBackground(new java.awt.Color(204, 204, 204));
        JugadorPuntacion3.setPreferredSize(new java.awt.Dimension(500, 130));
        JugadorPuntacion3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugadorP3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblJugadorP3.setText("Jugador:");
        JugadorPuntacion3.add(lblJugadorP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 280, -1));
        JugadorPuntacion3.add(lblAvatarP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        JugadorPuntacion3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 0, 50, 130));

        lblPuntosP3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblPuntosP3.setText("Puntos Restantes:");
        JugadorPuntacion3.add(lblPuntosP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 190, -1));

        JugadorPuntacion2.setBackground(new java.awt.Color(204, 204, 204));
        JugadorPuntacion2.setPreferredSize(new java.awt.Dimension(500, 130));
        JugadorPuntacion2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugadorP2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblJugadorP2.setText("Jugador:");
        JugadorPuntacion2.add(lblJugadorP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 290, -1));
        JugadorPuntacion2.add(lblAvatarP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        JugadorPuntacion2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 50, 130));

        lblPuntosP2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblPuntosP2.setText("Puntos Restantes:");
        JugadorPuntacion2.add(lblPuntosP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 190, -1));

        JugadorPuntacion4.setBackground(new java.awt.Color(204, 204, 204));
        JugadorPuntacion4.setPreferredSize(new java.awt.Dimension(500, 130));
        JugadorPuntacion4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugadorP4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblJugadorP4.setText("Jugador:");
        JugadorPuntacion4.add(lblJugadorP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 280, -1));
        JugadorPuntacion4.add(lblAvatarP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        JugadorPuntacion4.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 50, 130));

        lblPuntosP4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblPuntosP4.setText("Puntos Restantes:");
        JugadorPuntacion4.add(lblPuntosP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 190, -1));

        JugadorPuntacion1.setBackground(new java.awt.Color(204, 204, 204));
        JugadorPuntacion1.setPreferredSize(new java.awt.Dimension(500, 130));
        JugadorPuntacion1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugadorP1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblJugadorP1.setText("Jugador:");
        JugadorPuntacion1.add(lblJugadorP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 290, -1));
        JugadorPuntacion1.add(lblAvatarP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        JugadorPuntacion1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 0, 50, 130));

        lblPuntosP1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblPuntosP1.setText("Puntos Restantes:");
        JugadorPuntacion1.add(lblPuntosP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 190, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblCoronitaBroce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafico/coronita_bronce.png"))); // NOI18N

        lblCoronitaDorada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafico/coronita.png"))); // NOI18N

        lblCoronitaPlateada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafico/coronita_plata.png"))); // NOI18N

        javax.swing.GroupLayout pantallaPuntuacionesLayout = new javax.swing.GroupLayout(pantallaPuntuaciones);
        pantallaPuntuaciones.setLayout(pantallaPuntuacionesLayout);
        pantallaPuntuacionesLayout.setHorizontalGroup(
            pantallaPuntuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantallaPuntuacionesLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(pantallaPuntuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCoronitaDorada, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCoronitaBroce, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCoronitaPlateada, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(53, 53, 53)
                .addGroup(pantallaPuntuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pantallaPuntuacionesLayout.createSequentialGroup()
                        .addGroup(pantallaPuntuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JugadorPuntacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JugadorPuntacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JugadorPuntacion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(284, 284, 284))
                    .addGroup(pantallaPuntuacionesLayout.createSequentialGroup()
                        .addComponent(JugadorPuntacion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(102, 102, 102))))
        );
        pantallaPuntuacionesLayout.setVerticalGroup(
            pantallaPuntuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaPuntuacionesLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pantallaPuntuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JugadorPuntacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCoronitaDorada))
                .addGroup(pantallaPuntuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pantallaPuntuacionesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(JugadorPuntacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pantallaPuntuacionesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblCoronitaPlateada)
                        .addGap(22, 22, 22)
                        .addGroup(pantallaPuntuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(JugadorPuntacion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCoronitaBroce))))
                .addGap(12, 12, 12)
                .addComponent(JugadorPuntacion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantallaespera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pantallaPuntuaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantallaespera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(pantallaPuntuaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

    }//GEN-LAST:event_formKeyReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        arrastrarFicha(evt);
    }//GEN-LAST:event_formMouseDragged

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased

        realizaMovimiento(evt);
    }//GEN-LAST:event_formMouseReleased

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        agarrarFicha(evt);
    }//GEN-LAST:event_formMousePressed

    private void btnRobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRobarActionPerformed
        robarFicha();
    }//GEN-LAST:event_btnRobarActionPerformed

    private void btnIniciarVotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarVotacionActionPerformed
        inicioVotacion();
    }//GEN-LAST:event_btnIniciarVotacionActionPerformed

    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        respuesta = true;
        respuestaVotacion();

    }//GEN-LAST:event_btnSiActionPerformed

    private void BtnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNoActionPerformed
        respuesta = false;
        respuestaVotacion();

    }//GEN-LAST:event_BtnNoActionPerformed

    private void btnPasarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasarTurnoActionPerformed
        presentador.pasarTurno();
    }//GEN-LAST:event_btnPasarTurnoActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        iniciarVotacionTerminarPartida();
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAbandonarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbandonarPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbandonarPartidaActionPerformed
    public void limpiarInformacion() {
        // Limpia los textos de los JLabels
        lblJugador1.setText("");
        lblJugador2.setText("");
        lblJugador3.setText("");
        lblJugador4.setText("");
        
        // Limpia los iconos de los JLabels
        lblAvatar1.setIcon(null);
        lblAvatar2.setIcon(null);
        lblAvatar3.setIcon(null);
        lblAvatar4.setIcon(null);
    }
    public void limpiarInformacionP() {
        // Limpia los textos de los JLabels
        lblJugadorP1.setText("");
        lblJugadorP2.setText("");
        lblJugadorP3.setText("");
        lblJugadorP4.setText("");
        
        // Limpia los iconos de los JLabels
        lblAvatarP1.setIcon(null);
        lblAvatarP2.setIcon(null);
        lblAvatarP3.setIcon(null);
        lblAvatarP4.setIcon(null);
    }
    public void TerminarPartida(){
        this.remove(tablero);
        pantallaPuntuaciones.setVisible(true);
        pantallaespera.setVisible(false);
        this.setContentPane(pantallaPuntuaciones);
        this.repaint();
        
    }

    public void mostrarJugadores() {
        List<JugadorDTO> list = presentador.listaJugadores();
        limpiarInformacion();
        if (!partidaIniciada) {
            for (int i = 0; i < list.size(); i++) {
                if (i == 0) {
                    lblJugador1.setText(list.get(0).getNombre());
                    ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(list.get(0).getAvatar()));
                    ImageIcon iconoRedimensionado = new ImageIcon(iconoOriginal.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH));
                    lblAvatar1.setIcon(iconoRedimensionado);
                }
                if (i == 1) {
                    lblJugador2.setText(list.get(1).getNombre());
                    ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(list.get(1).getAvatar()));
                    ImageIcon iconoRedimensionado = new ImageIcon(iconoOriginal.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH));
                    lblAvatar2.setIcon(iconoRedimensionado);
                }
                if (i == 2) {
                    lblJugador3.setText(list.get(2).getNombre());
                    ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(list.get(2).getAvatar()));
                    ImageIcon iconoRedimensionado = new ImageIcon(iconoOriginal.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH));
                    lblAvatar3.setIcon(iconoRedimensionado);
                }
                if (i == 3) {
                    lblJugador4.setText(list.get(3).getNombre());
                    ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(list.get(3).getAvatar()));
                    ImageIcon iconoRedimensionado = new ImageIcon(iconoOriginal.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH));
                    lblAvatar4.setIcon(iconoRedimensionado);
                }
            }
        }

        this.setPartidaTablero();
//        tablero.setPartida(presentador.getPartida());
        tablero.repaint();
    }

    public boolean isVotar() {
        return votar;
    }

    public void setVotar(boolean votar) {
        this.votar = votar;
    }
    
    
    public void mostrarPuntuaciones(List<JugadorDTO> jugadores) {
        List<JugadorDTO> list = jugadores;
        List<Integer> puntaciones = new ArrayList<>();
        for (JugadorDTO jugadorDTO : jugadores) {

            int total = 0;
            for (FichaDTO fichaDTO : jugadorDTO.getFichasJugador()) {
                total += fichaDTO.getPuntoArriba();
                total += fichaDTO.getPuntoAbajo();
            }
            if (jugadorDTO.getFichasJugador().isEmpty()) {
                total=-1;
            }
            puntaciones.add(total);
        }
            limpiarInformacionP();
            JugadorPuntacion1.setVisible(false);
            JugadorPuntacion2.setVisible(false);
            JugadorPuntacion3.setVisible(false);
            JugadorPuntacion4.setVisible(false);
            lblCoronitaBroce.setVisible(false);
            lblCoronitaDorada.setVisible(false);
            lblCoronitaPlateada.setVisible(false);
            for (int i = 0; i < list.size(); i++) {
                if (i == 0) {
                    JugadorPuntacion1.setVisible(true);
                    lblJugadorP1.setText("Jugador: "+list.get(0).getNombre());
                    ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(list.get(0).getAvatar()));
                    ImageIcon iconoRedimensionado = new ImageIcon(iconoOriginal.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH));
                    lblAvatarP1.setIcon(iconoRedimensionado);
                    lblCoronitaDorada.setVisible(true);
                    if (puntaciones.get(i)==-1) {
                        lblPuntosP1.setText("");
                    }else{
                        lblPuntosP1.setText("Puntos Restantes: "+puntaciones.get(i));
                    }
                    
                }
                if (i == 1) {
                    JugadorPuntacion2.setVisible(true);
                    lblJugadorP2.setText("Jugador: "+list.get(1).getNombre());
                    ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(list.get(1).getAvatar()));
                    ImageIcon iconoRedimensionado = new ImageIcon(iconoOriginal.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH));
                    lblAvatarP2.setIcon(iconoRedimensionado);
                    lblCoronitaPlateada.setVisible(true);
                    lblPuntosP2.setText("Puntos Restantes: "+puntaciones.get(i));
                }
                if (i == 2) {
                    JugadorPuntacion3.setVisible(true);
                    lblJugadorP3.setText("Jugador: "+list.get(2).getNombre());
                    ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(list.get(2).getAvatar()));
                    ImageIcon iconoRedimensionado = new ImageIcon(iconoOriginal.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH));
                    lblAvatarP3.setIcon(iconoRedimensionado);
                    lblCoronitaBroce.setVisible(true);
                    lblPuntosP3.setText("Puntos Restantes: "+puntaciones.get(i));
                }
                if (i == 3) {
                    JugadorPuntacion4.setVisible(true);
                    lblJugadorP4.setText("Jugador: "+list.get(3).getNombre());
                    ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(list.get(3).getAvatar()));
                    ImageIcon iconoRedimensionado = new ImageIcon(iconoOriginal.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH));
                    lblAvatarP4.setIcon(iconoRedimensionado);
                    lblPuntosP4.setText("Puntos Restantes: "+puntaciones.get(i));
                }
            }
        

        this.setPartidaTablero();
//        tablero.setPartida(presentador.getPartida());
        tablero.repaint();
    }
    public void setPartidaTablero() {
        tablero.setPartida(presentador.getPartida());
        tablero.repintarFichasJugador();
    }

    public void pintarFichas() {
        tablero.repintarFichasJugador();
    }

    public void robarFicha() {
        if (!presentador.isTurno()) { 
            return;
        }
        presentador.robarFicha();
    }

    public int validaHitbox(MouseEvent e) {
        return tablero.validaHitbox(e);
    }

    public void mostrarMensajeError(String error) {
        JOptionPane.showMessageDialog(rootPane, error);
    }

    public void agarrarFicha(MouseEvent evt) {

        Insets insets = this.getInsets();
        int adjustedX = evt.getX() - insets.left;
        int adjustedY = evt.getY() - insets.top;
        tablero.moverFicha(new MouseEvent(evt.getComponent(), evt.getID(), evt.getWhen(), evt.getModifiersEx(), adjustedX, adjustedY, evt.getClickCount(), evt.isPopupTrigger()));

    }

    public void arrastrarFicha(MouseEvent evt) {

        Insets insets = this.getInsets();
        int adjustedX = evt.getX() - insets.left;
        int adjustedY = evt.getY() - insets.top;
        tablero.arrastrarFicha(new MouseEvent(evt.getComponent(), evt.getID(), evt.getWhen(), evt.getModifiersEx(), adjustedX, adjustedY, evt.getClickCount(), evt.isPopupTrigger()));

    }

    public void realizaMovimiento(MouseEvent evt) {

        Insets insets = this.getInsets();
        int adjustedX = evt.getX() - insets.left;
        int adjustedY = evt.getY() - insets.top;

        int valida = validaHitbox(new MouseEvent(evt.getComponent(), evt.getID(), evt.getWhen(), evt.getModifiersEx(), adjustedX, adjustedY, evt.getClickCount(), evt.isPopupTrigger()));
        if (valida == 0) {

            return;
        }
        if (!presentador.isTurno()) {
            tablero.resetearFichaSeleccionada();
            return;
        }
        FichaDTO ficha = tablero.obtenerFichaSeleccionada();
        FichaTableroDTO f = new FichaTableroDTO(ficha.getImagen(), ficha.getPuntoAbajo(), ficha.getPuntoArriba());

        presentador.realizaMovimiento(f, valida);
//        boolean validaFicha = false;
//
//        switch (valida) {
//            case 1:
//                validaFicha = presentador.realizaMovimiento(f, valida);
//                break;
//            case 2:
//                validaFicha = presentador.realizaMovimiento(f, valida);
//                break;
//            case 3:
//                validaFicha = presentador.realizaMovimiento(f, valida);
//                break;
//        }
//        if (!validaFicha) {
//            tablero.resetearFichaSeleccionada();
//        }
//        if (validaFicha) {
//            switch (valida) {
//                case 1:
//                    tablero.colocarInicial(f);
//                    break;
//                case 2:
//                    tablero.colocarTrenDerecha(f);
//                    break;
//                case 3:
//                    tablero.colocarTrenIzquierda(f);
//                    break;
//            }
////            presentador.eliminarFichaJugador(ficha);
//        }
    }

    public void regresaFicha() {
        tablero.resetearFichaSeleccionada();
    }

    public void colocarFicha(FichaTableroDTO f, int zona) {
        
        switch (zona) {
            case 1:
                System.out.println("inicial");
                tablero.colocarInicial(f);
                break;
            case 2:
                System.out.println("derecha");
                tablero.colocarTrenDerecha(f);
                break;
            case 3:
                System.out.println("izquierda");
                tablero.colocarTrenIzquierda(f);
                break;
        }
    }

    public void iniciarJuego() {
        Jugador1.setVisible(false);
        Jugador2.setVisible(false);
        Jugador3.setVisible(false);
        Jugador4.setVisible(false);

        add(tablero);
//        presentador.iniciarPartida();
        this.partidaIniciada = true;

        this.setContentPane(tablero);

//        tablero.setLayout(null);
        tablero.add(btnRobar);
        btnRobar.setVisible(true);
        tablero.add(btnPasarTurno);
        tablero.add(btnTerminar);
        btnPasarTurno.setVisible(true);
        btnPasarTurno.setBounds(5, 5, 100, 30);
        btnTerminar.setVisible(true);
        btnTerminar.setBounds(150, 5, 200, 30);
        Rectangle s = Votacion.getBounds();
        tablero.add(Votacion);

        Votacion.setVisible(false);

//        tablero.agregarFichasIniciales();
    }

    public void votacion() {
        votar=true;
        btnIniciarVotacion.setVisible(false);
        Jugador1.setVisible(false);
        Jugador2.setVisible(false);
        Jugador3.setVisible(false);
        Jugador4.setVisible(false);
        Votacion.setVisible(true);
        BtnNo.setEnabled(true);
        btnSi.setEnabled(true);
        Votacion.setBounds(300, 300, 200, 30);
    }

    public void votacionNoaceptada() {
        Votacion.setVisible(false);
        btnIniciarVotacion.setVisible(true);
        Jugador1.setVisible(true);
        Jugador2.setVisible(true);
        Jugador3.setVisible(true);
        Jugador4.setVisible(true);
        btnSi.setEnabled(true);
        BtnNo.setEnabled(true);
    }

    public void respuestaVotacion() {
        presentador.respuestaVotacion(respuesta);
        BtnNo.setEnabled(false);
        btnSi.setEnabled(false);
    }

    public void activarBotones() {
        BtnNo.setEnabled(true);
        btnSi.setEnabled(true);
    }

    public void mostrarMensaje() {
        JOptionPane.showMessageDialog(this, "Faltas jugadores");
    }

    public void inicioVotacion() {
        presentador.iniciarVotacion();
    }

    public void iniciarVotacionTerminarPartida() {
        presentador.iniciarVotacionTerminarPartida();
    }

    public boolean isTurno() {
        return presentador.isTurno();
    }

    public void asignarJugadorJugando(JugadorDTO jugador) {
        tablero.setJugador(jugador);
        this.pintarFichas();

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNo;
    private javax.swing.JPanel Jugador1;
    private javax.swing.JPanel Jugador2;
    private javax.swing.JPanel Jugador3;
    private javax.swing.JPanel Jugador4;
    private javax.swing.JPanel JugadorPuntacion1;
    private javax.swing.JPanel JugadorPuntacion2;
    private javax.swing.JPanel JugadorPuntacion3;
    private javax.swing.JPanel JugadorPuntacion4;
    private javax.swing.JPanel Votacion;
    private javax.swing.JButton btnAbandonarPartida;
    private javax.swing.JButton btnIniciarVotacion;
    private javax.swing.JButton btnPasarTurno;
    private javax.swing.JButton btnRobar;
    private javax.swing.JButton btnSi;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblAvatar1;
    private javax.swing.JLabel lblAvatar2;
    private javax.swing.JLabel lblAvatar3;
    private javax.swing.JLabel lblAvatar4;
    private javax.swing.JLabel lblAvatarP1;
    private javax.swing.JLabel lblAvatarP2;
    private javax.swing.JLabel lblAvatarP3;
    private javax.swing.JLabel lblAvatarP4;
    private javax.swing.JLabel lblCoronitaBroce;
    private javax.swing.JLabel lblCoronitaDorada;
    private javax.swing.JLabel lblCoronitaPlateada;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JLabel lblJugador3;
    private javax.swing.JLabel lblJugador4;
    private javax.swing.JLabel lblJugadorP1;
    private javax.swing.JLabel lblJugadorP2;
    private javax.swing.JLabel lblJugadorP3;
    private javax.swing.JLabel lblJugadorP4;
    private javax.swing.JLabel lblPuntosP1;
    private javax.swing.JLabel lblPuntosP2;
    private javax.swing.JLabel lblPuntosP3;
    private javax.swing.JLabel lblPuntosP4;
    private javax.swing.JPanel pantallaPuntuaciones;
    private javax.swing.JPanel pantallaespera;
    // End of variables declaration//GEN-END:variables

}
