/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MVP.Vista;

import Grafico.TableroGrafico;
import MVP.Presentador.IPresentacionJuego;

import dominio_dominodto.FichaDTO;
import dominio_dominodto.FichaTableroDTO;
import dominio_dominodto.JugadorDTO;
import dominio_dominodto.PartidaDTO;
import java.awt.Color;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Rectangle;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author diego
 */
public class VistaJuego extends javax.swing.JFrame {

    private IPresentacionJuego presentador;

    private TableroGrafico tablero;
    private boolean respuesta;
    private boolean partidaIniciada = false;
    private boolean votar = false;

    /**
     * Creates new form VistaJuego
     */
    public VistaJuego(IPresentacionJuego presentador) {

        this.presentador = presentador;
        tablero = new TableroGrafico(this);
        initComponents();
        btnRobar.setVisible(false);
        Votacion.setVisible(false);
        btnTerminar.setVisible(false);
        btnPasarTurno.setVisible(false);
        pantallaPuntuaciones.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantallaespera = new javax.swing.JPanel();
        Votacion = new javax.swing.JPanel();
        BtnNo = new javax.swing.JButton();
        btnSi = new javax.swing.JButton();
        lblVotacion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRobar = new javax.swing.JButton();
        Jugador3 = new javax.swing.JPanel();
        lblJugador3 = new javax.swing.JLabel();
        lblAvatar3 = new javax.swing.JLabel();
        panel4 = new javax.swing.JLabel();
        Jugador2 = new javax.swing.JPanel();
        lblJugador2 = new javax.swing.JLabel();
        lblAvatar2 = new javax.swing.JLabel();
        panel2 = new javax.swing.JLabel();
        Jugador4 = new javax.swing.JPanel();
        lblJugador4 = new javax.swing.JLabel();
        lblAvatar4 = new javax.swing.JLabel();
        panel3 = new javax.swing.JLabel();
        Jugador1 = new javax.swing.JPanel();
        lblJugador1 = new javax.swing.JLabel();
        lblAvatar1 = new javax.swing.JLabel();
        panel1 = new javax.swing.JLabel();
        btnIniciarVotacion = new javax.swing.JButton();
        btnPasarTurno = new javax.swing.JButton();
        btnTerminar = new javax.swing.JButton();
        btnAbandonarPartida = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pantallaPuntuaciones = new javax.swing.JPanel();
        JugadorPuntacion3 = new javax.swing.JPanel();
        lblJugadorP3 = new javax.swing.JLabel();
        lblAvatarP3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lblPuntosP3 = new javax.swing.JLabel();
        JugadorPuntacion2 = new javax.swing.JPanel();
        lblJugadorP2 = new javax.swing.JLabel();
        lblAvatarP2 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        lblPuntosP2 = new javax.swing.JLabel();
        JugadorPuntacion4 = new javax.swing.JPanel();
        lblJugadorP4 = new javax.swing.JLabel();
        lblAvatarP4 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        lblPuntosP4 = new javax.swing.JLabel();
        JugadorPuntacion1 = new javax.swing.JPanel();
        lblJugadorP1 = new javax.swing.JLabel();
        lblAvatarP1 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        lblPuntosP1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblCoronitaBroce = new javax.swing.JLabel();
        lblCoronitaDorada = new javax.swing.JLabel();
        lblCoronitaPlateada = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 0));
        setMinimumSize(new java.awt.Dimension(1300, 590));
        setPreferredSize(new java.awt.Dimension(1300, 590));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        pantallaespera.setBackground(new java.awt.Color(0, 153, 0));
        pantallaespera.setForeground(new java.awt.Color(0, 153, 0));
        pantallaespera.setMinimumSize(new java.awt.Dimension(1300, 590));
        pantallaespera.setName(""); // NOI18N
        pantallaespera.setPreferredSize(new java.awt.Dimension(1300, 590));
        pantallaespera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Votacion.setMinimumSize(new java.awt.Dimension(500, 230));
        Votacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafico/Botones/NoN.png"))); // NOI18N
        BtnNo.setBorderPainted(false);
        BtnNo.setContentAreaFilled(false);
        BtnNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnNoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnNoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnNoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnNoMouseReleased(evt);
            }
        });
        BtnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNoActionPerformed(evt);
            }
        });
        Votacion.add(BtnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 250, 90));

        btnSi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafico/Botones/SiN.png"))); // NOI18N
        btnSi.setBorderPainted(false);
        btnSi.setContentAreaFilled(false);
        btnSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSiMouseReleased(evt);
            }
        });
        btnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiActionPerformed(evt);
            }
        });
        Votacion.add(btnSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 240, 90));

        lblVotacion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblVotacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafico/Botones/QUIERES.png"))); // NOI18N
        Votacion.add(lblVotacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 510, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafico/Botones/votacion.png"))); // NOI18N
        Votacion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 230));

        pantallaespera.add(Votacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        btnRobar.setText("Robar Ficha");
        btnRobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRobarActionPerformed(evt);
            }
        });
        pantallaespera.add(btnRobar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, 205, -1));

        Jugador3.setBackground(new java.awt.Color(204, 204, 204));
        Jugador3.setPreferredSize(new java.awt.Dimension(500, 130));
        Jugador3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugador3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJugador3.setText("Jugador:");
        lblJugador3.setPreferredSize(new java.awt.Dimension(200, 20));
        Jugador3.add(lblJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 44, -1, -1));
        Jugador3.add(lblAvatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafico/Botones/Group 2 (3).png"))); // NOI18N
        Jugador3.add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pantallaespera.add(Jugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, 120));

        Jugador2.setBackground(new java.awt.Color(204, 204, 204));
        Jugador2.setPreferredSize(new java.awt.Dimension(500, 130));
        Jugador2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugador2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJugador2.setText("Jugador:");
        lblJugador2.setPreferredSize(new java.awt.Dimension(200, 20));
        Jugador2.add(lblJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 44, -1, -1));
        Jugador2.add(lblAvatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafico/Botones/Group 2 (3).png"))); // NOI18N
        Jugador2.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pantallaespera.add(Jugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, 120));

        Jugador4.setBackground(new java.awt.Color(204, 204, 204));
        Jugador4.setPreferredSize(new java.awt.Dimension(500, 130));
        Jugador4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugador4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJugador4.setText("Jugador:");
        lblJugador4.setPreferredSize(new java.awt.Dimension(200, 20));
        Jugador4.add(lblJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 44, -1, -1));
        Jugador4.add(lblAvatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafico/Botones/Group 2 (3).png"))); // NOI18N
        Jugador4.add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pantallaespera.add(Jugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, 120));

        Jugador1.setBackground(new java.awt.Color(204, 204, 204));
        Jugador1.setPreferredSize(new java.awt.Dimension(500, 130));
        Jugador1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugador1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJugador1.setText("Jugador:");
        lblJugador1.setPreferredSize(new java.awt.Dimension(200, 20));
        Jugador1.add(lblJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 44, -1, -1));
        Jugador1.add(lblAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafico/Botones/Group 2 (3).png"))); // NOI18N
        Jugador1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pantallaespera.add(Jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 120));

        btnIniciarVotacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafico/Botones/IniciarVN.png"))); // NOI18N
        btnIniciarVotacion.setBorderPainted(false);
        btnIniciarVotacion.setContentAreaFilled(false);
        btnIniciarVotacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIniciarVotacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIniciarVotacionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnIniciarVotacionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnIniciarVotacionMouseReleased(evt);
            }
        });
        btnIniciarVotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarVotacionActionPerformed(evt);
            }
        });
        pantallaespera.add(btnIniciarVotacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 250, 90));

        btnPasarTurno.setText("Pasar Turno");
        btnPasarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasarTurnoActionPerformed(evt);
            }
        });
        pantallaespera.add(btnPasarTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 260, 205, -1));

        btnTerminar.setText("Terminar Partida");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });
        pantallaespera.add(btnTerminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 290, -1, -1));

        btnAbandonarPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafico/Botones/AbandonarPN.png"))); // NOI18N
        btnAbandonarPartida.setBorderPainted(false);
        btnAbandonarPartida.setContentAreaFilled(false);
        btnAbandonarPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAbandonarPartidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAbandonarPartidaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAbandonarPartidaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAbandonarPartidaMouseReleased(evt);
            }
        });
        btnAbandonarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbandonarPartidaActionPerformed(evt);
            }
        });
        pantallaespera.add(btnAbandonarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 270, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafico/Botones/Frame 1 (16) (1).png"))); // NOI18N
        pantallaespera.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pantallaPuntuaciones.setBackground(new java.awt.Color(0, 153, 0));
        pantallaPuntuaciones.setForeground(new java.awt.Color(0, 153, 0));
        pantallaPuntuaciones.setMinimumSize(new java.awt.Dimension(1300, 590));
        pantallaPuntuaciones.setPreferredSize(new java.awt.Dimension(1300, 590));
        pantallaPuntuaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JugadorPuntacion3.setBackground(new java.awt.Color(204, 204, 204));
        JugadorPuntacion3.setPreferredSize(new java.awt.Dimension(500, 130));
        JugadorPuntacion3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugadorP3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblJugadorP3.setText("Jugador:");
        JugadorPuntacion3.add(lblJugadorP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 280, -1));
        JugadorPuntacion3.add(lblAvatarP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        JugadorPuntacion3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 0, 50, 130));

        lblPuntosP3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblPuntosP3.setText("Puntos Restantes:");
        JugadorPuntacion3.add(lblPuntosP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 190, -1));

        pantallaPuntuaciones.add(JugadorPuntacion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, 120));

        JugadorPuntacion2.setBackground(new java.awt.Color(204, 204, 204));
        JugadorPuntacion2.setPreferredSize(new java.awt.Dimension(500, 130));
        JugadorPuntacion2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugadorP2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblJugadorP2.setText("Jugador:");
        JugadorPuntacion2.add(lblJugadorP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 290, -1));
        JugadorPuntacion2.add(lblAvatarP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        JugadorPuntacion2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 50, 130));

        lblPuntosP2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblPuntosP2.setText("Puntos Restantes:");
        JugadorPuntacion2.add(lblPuntosP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 190, -1));

        pantallaPuntuaciones.add(JugadorPuntacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, 120));

        JugadorPuntacion4.setBackground(new java.awt.Color(204, 204, 204));
        JugadorPuntacion4.setPreferredSize(new java.awt.Dimension(500, 130));
        JugadorPuntacion4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugadorP4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblJugadorP4.setText("Jugador:");
        JugadorPuntacion4.add(lblJugadorP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 280, -1));
        JugadorPuntacion4.add(lblAvatarP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        JugadorPuntacion4.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 50, 130));

        lblPuntosP4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblPuntosP4.setText("Puntos Restantes:");
        JugadorPuntacion4.add(lblPuntosP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 190, -1));

        pantallaPuntuaciones.add(JugadorPuntacion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, 120));

        JugadorPuntacion1.setBackground(new java.awt.Color(204, 204, 204));
        JugadorPuntacion1.setPreferredSize(new java.awt.Dimension(500, 130));
        JugadorPuntacion1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugadorP1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblJugadorP1.setText("Jugador:");
        JugadorPuntacion1.add(lblJugadorP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 290, -1));
        JugadorPuntacion1.add(lblAvatarP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        JugadorPuntacion1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 0, 50, 130));

        lblPuntosP1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblPuntosP1.setText("Puntos Restantes:");
        JugadorPuntacion1.add(lblPuntosP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 190, -1));

        pantallaPuntuaciones.add(JugadorPuntacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, 120));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pantallaPuntuaciones.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 280, -1, -1));

        lblCoronitaBroce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafico/coronita_bronce.png"))); // NOI18N
        pantallaPuntuaciones.add(lblCoronitaBroce, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        lblCoronitaDorada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafico/coronita.png"))); // NOI18N
        pantallaPuntuaciones.add(lblCoronitaDorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, 130));

        lblCoronitaPlateada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafico/coronita_plata.png"))); // NOI18N
        pantallaPuntuaciones.add(lblCoronitaPlateada, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, 130));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafico/Botones/Frame 1 (16) (1).png"))); // NOI18N
        pantallaPuntuaciones.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantallaespera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pantallaPuntuaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantallaespera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(pantallaPuntuaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

    }//GEN-LAST:event_formKeyReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        arrastrarFicha(evt);
    }//GEN-LAST:event_formMouseDragged

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased

        realizaMovimiento(evt);
    }//GEN-LAST:event_formMouseReleased

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        agarrarFicha(evt);
    }//GEN-LAST:event_formMousePressed

    private void btnRobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRobarActionPerformed
        robarFicha();
    }//GEN-LAST:event_btnRobarActionPerformed

    private void btnIniciarVotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarVotacionActionPerformed
        inicioVotacion();
    }//GEN-LAST:event_btnIniciarVotacionActionPerformed

    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        respuesta = true;
        respuestaVotacion();

    }//GEN-LAST:event_btnSiActionPerformed

    private void BtnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNoActionPerformed
        respuesta = false;
        respuestaVotacion();

    }//GEN-LAST:event_BtnNoActionPerformed

    private void btnPasarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasarTurnoActionPerformed
        presentador.pasarTurno();
    }//GEN-LAST:event_btnPasarTurnoActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        iniciarVotacionTerminarPartida();
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAbandonarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbandonarPartidaActionPerformed
        presentador.salirPartida();

    }//GEN-LAST:event_btnAbandonarPartidaActionPerformed

    private void btnSiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiMouseReleased
        btnSi.setIcon(new ImageIcon(getClass().getResource("/Grafico/Botones/SiG.png")));
    }//GEN-LAST:event_btnSiMouseReleased

    private void btnSiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiMouseEntered
        btnSi.setIcon(new ImageIcon(getClass().getResource("/Grafico/Botones/SiG.png")));
    }//GEN-LAST:event_btnSiMouseEntered

    private void btnSiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiMousePressed
        btnSi.setIcon(new ImageIcon(getClass().getResource("/Grafico/Botones/SiN.png")));
    }//GEN-LAST:event_btnSiMousePressed

    private void btnSiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiMouseExited
        btnSi.setIcon(new ImageIcon(getClass().getResource("/Grafico/Botones/SiN.png")));
    }//GEN-LAST:event_btnSiMouseExited

    private void BtnNoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnNoMouseEntered
       BtnNo.setIcon(new ImageIcon(getClass().getResource("/Grafico/Botones/NoG.png")));
    }//GEN-LAST:event_BtnNoMouseEntered

    private void BtnNoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnNoMouseReleased
       BtnNo.setIcon(new ImageIcon(getClass().getResource("/Grafico/Botones/NoG.png")));
    }//GEN-LAST:event_BtnNoMouseReleased

    private void BtnNoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnNoMousePressed
       BtnNo.setIcon(new ImageIcon(getClass().getResource("/Grafico/Botones/NoN.png")));
    }//GEN-LAST:event_BtnNoMousePressed

    private void BtnNoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnNoMouseExited
        BtnNo.setIcon(new ImageIcon(getClass().getResource("/Grafico/Botones/NoN.png")));
    }//GEN-LAST:event_BtnNoMouseExited

    private void btnIniciarVotacionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarVotacionMouseReleased
       btnIniciarVotacion.setIcon(new ImageIcon(getClass().getResource("/Grafico/Botones/IniciarVG.png")));
    }//GEN-LAST:event_btnIniciarVotacionMouseReleased

    private void btnIniciarVotacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarVotacionMouseEntered
       btnIniciarVotacion.setIcon(new ImageIcon(getClass().getResource("/Grafico/Botones/IniciarVG.png")));
    }//GEN-LAST:event_btnIniciarVotacionMouseEntered

    private void btnIniciarVotacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarVotacionMouseExited
        btnIniciarVotacion.setIcon(new ImageIcon(getClass().getResource("/Grafico/Botones/IniciarVN.png")));
    }//GEN-LAST:event_btnIniciarVotacionMouseExited

    private void btnIniciarVotacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarVotacionMousePressed
         btnIniciarVotacion.setIcon(new ImageIcon(getClass().getResource("/Grafico/Botones/IniciarVN.png")));
    }//GEN-LAST:event_btnIniciarVotacionMousePressed

    private void btnAbandonarPartidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbandonarPartidaMouseEntered
        btnAbandonarPartida.setIcon(new ImageIcon(getClass().getResource("/Grafico/Botones/AbandonarPG.png")));
    }//GEN-LAST:event_btnAbandonarPartidaMouseEntered

    private void btnAbandonarPartidaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbandonarPartidaMouseReleased
        btnAbandonarPartida.setIcon(new ImageIcon(getClass().getResource("/Grafico/Botones/AbandonarPG.png")));
    }//GEN-LAST:event_btnAbandonarPartidaMouseReleased

    private void btnAbandonarPartidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbandonarPartidaMouseExited
       btnAbandonarPartida.setIcon(new ImageIcon(getClass().getResource("/Grafico/Botones/AbandonarPN.png")));
    }//GEN-LAST:event_btnAbandonarPartidaMouseExited

    private void btnAbandonarPartidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbandonarPartidaMousePressed
      btnAbandonarPartida.setIcon(new ImageIcon(getClass().getResource("/Grafico/Botones/AbandonarPN.png")));
    }//GEN-LAST:event_btnAbandonarPartidaMousePressed
    public void limpiarInformacion() {
        // Limpia los textos de los JLabels
        lblJugador1.setText("");
        lblJugador2.setText("");
        lblJugador3.setText("");
        lblJugador4.setText("");
        lblJugador1.setBounds(lblJugador1.getX(), 60, 200, 20);
        lblJugador2.setBounds(lblJugador2.getX(), 60, 200, 20);
        lblJugador3.setBounds(lblJugador3.getX(), 60, 200, 20);
        lblJugador4.setBounds(lblJugador4.getX(), 60, 200, 20);
        // Limpia los iconos de los JLabels
        lblAvatar1.setIcon(null);
        lblAvatar2.setIcon(null);
        lblAvatar3.setIcon(null);
        lblAvatar4.setIcon(null);
        lblAvatar1.setBounds(lblAvatar1.getX(), lblAvatar1.getY(), 130, 120);
        lblAvatar2.setBounds(lblAvatar2.getX(), lblAvatar2.getY(), 130, 120);
        lblAvatar3.setBounds(lblAvatar3.getX(), lblAvatar3.getY(), 130, 120);
        lblAvatar4.setBounds(lblAvatar4.getX(), lblAvatar4.getY(), 130, 120);
    }

    public void limpiarInformacionP() {
        // Limpia los textos de los JLabels
        lblJugadorP1.setText("");
        lblJugadorP2.setText("");
        lblJugadorP3.setText("");
        lblJugadorP4.setText("");

        // Limpia los iconos de los JLabels
        lblAvatarP1.setIcon(null);
        lblAvatarP2.setIcon(null);
        lblAvatarP3.setIcon(null);
        lblAvatarP4.setIcon(null);
    }

    private void reproducirSonido(String ruta) {
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(getClass().getResourceAsStream(ruta));
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void TerminarPartida() {
        this.remove(tablero);
        pantallaPuntuaciones.setVisible(true);
        pantallaespera.setVisible(false);
        this.setContentPane(pantallaPuntuaciones);
        this.repaint();

    }

    public void mostrarJugadores() {
        List<JugadorDTO> list = presentador.listaJugadores();
        System.out.println("hay " + list.size());
        limpiarInformacion();
        if (!partidaIniciada) {
            for (int i = 0; i < list.size(); i++) {
                if (i == 0) {

                    lblJugador1.setText(list.get(i).getNombre());
                    ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(list.get(i).getAvatar()));
                    ImageIcon iconoRedimensionado = new ImageIcon(iconoOriginal.getImage().getScaledInstance(130, 120, Image.SCALE_SMOOTH));
                    lblAvatar1.setIcon(iconoRedimensionado);
                }
                if (i == 1) {

                    lblJugador2.setText(list.get(i).getNombre());

                    ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(list.get(i).getAvatar()));
                    ImageIcon iconoRedimensionado = new ImageIcon(iconoOriginal.getImage().getScaledInstance(130, 120, Image.SCALE_SMOOTH));
                    lblAvatar2.setIcon(iconoRedimensionado);
                }
                if (i == 2) {

                    lblJugador3.setText(list.get(i).getNombre());
                    ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(list.get(i).getAvatar()));
                    ImageIcon iconoRedimensionado = new ImageIcon(iconoOriginal.getImage().getScaledInstance(130, 120, Image.SCALE_SMOOTH));
                    lblAvatar3.setIcon(iconoRedimensionado);
                }
                if (i == 3) {

                    lblJugador4.setText(list.get(i).getNombre());
                    ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(list.get(i).getAvatar()));
                    ImageIcon iconoRedimensionado = new ImageIcon(iconoOriginal.getImage().getScaledInstance(130, 120, Image.SCALE_SMOOTH));
                    lblAvatar4.setIcon(iconoRedimensionado);
                }
            }
        }

        this.setPartidaTablero();
//        tablero.setPartida(presentador.getPartida());
        tablero.repaint();
        Jugador1.repaint();
        Jugador2.repaint();
        Jugador3.repaint();
        Jugador4.repaint();

    }

    public boolean isVotar() {
        return votar;
    }

    public void setVotar(boolean votar) {
        this.votar = votar;
    }

    public void mostrarPuntuaciones(List<JugadorDTO> jugadores) {
        List<JugadorDTO> list = jugadores;
        List<Integer> puntaciones = new ArrayList<>();
        for (JugadorDTO jugadorDTO : jugadores) {

            int total = 0;
            for (FichaDTO fichaDTO : jugadorDTO.getFichasJugador()) {
                total += fichaDTO.getPuntoArriba();
                total += fichaDTO.getPuntoAbajo();
            }
            if (jugadorDTO.getFichasJugador().isEmpty()) {
                total = -1;
            }
            puntaciones.add(total);
        }
        limpiarInformacionP();
        JugadorPuntacion1.setVisible(false);
        JugadorPuntacion2.setVisible(false);
        JugadorPuntacion3.setVisible(false);
        JugadorPuntacion4.setVisible(false);
        lblCoronitaBroce.setVisible(false);
        lblCoronitaDorada.setVisible(false);
        lblCoronitaPlateada.setVisible(false);
        for (int i = 0; i < list.size(); i++) {
            if (i == 0) {
                JugadorPuntacion1.setVisible(true);
                lblJugadorP1.setText("Jugador: " + list.get(0).getNombre());
                ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(list.get(0).getAvatar()));
                ImageIcon iconoRedimensionado = new ImageIcon(iconoOriginal.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH));
                lblAvatarP1.setIcon(iconoRedimensionado);
                lblCoronitaDorada.setVisible(true);
                if (puntaciones.get(i) == -1) {
                    lblPuntosP1.setText("");
                } else {
                    lblPuntosP1.setText("Puntos Restantes: " + puntaciones.get(i));
                }

            }
            if (i == 1) {
                JugadorPuntacion2.setVisible(true);
                lblJugadorP2.setText("Jugador: " + list.get(1).getNombre());
                ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(list.get(1).getAvatar()));
                ImageIcon iconoRedimensionado = new ImageIcon(iconoOriginal.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH));
                lblAvatarP2.setIcon(iconoRedimensionado);
                lblCoronitaPlateada.setVisible(true);
                lblPuntosP2.setText("Puntos Restantes: " + puntaciones.get(i));
            }
            if (i == 2) {
                JugadorPuntacion3.setVisible(true);
                lblJugadorP3.setText("Jugador: " + list.get(2).getNombre());
                ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(list.get(2).getAvatar()));
                ImageIcon iconoRedimensionado = new ImageIcon(iconoOriginal.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH));
                lblAvatarP3.setIcon(iconoRedimensionado);
                lblCoronitaBroce.setVisible(true);
                lblPuntosP3.setText("Puntos Restantes: " + puntaciones.get(i));
            }
            if (i == 3) {
                JugadorPuntacion4.setVisible(true);
                lblJugadorP4.setText("Jugador: " + list.get(3).getNombre());
                ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(list.get(3).getAvatar()));
                ImageIcon iconoRedimensionado = new ImageIcon(iconoOriginal.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH));
                lblAvatarP4.setIcon(iconoRedimensionado);
                lblPuntosP4.setText("Puntos Restantes: " + puntaciones.get(i));
            }
        }

        this.setPartidaTablero();
//        tablero.setPartida(presentador.getPartida());
        tablero.repaint();
    }

    public void setPartidaTablero() {
        tablero.setPartida(presentador.getPartida());
        tablero.repintarFichasJugador();
    }

    public void pintarFichas() {
        tablero.repintarFichasJugador();
    }

    public void robarFicha() {
        if (!presentador.isTurno()) {
            return;
        }
        presentador.robarFicha();
    }

    public int validaHitbox(MouseEvent e) {
        return tablero.validaHitbox(e);
    }

    public void mostrarMensajeError(String error) {
        JOptionPane.showMessageDialog(rootPane, error);
    }

    public void agarrarFicha(MouseEvent evt) {

        Insets insets = this.getInsets();
        int adjustedX = evt.getX() - insets.left;
        int adjustedY = evt.getY() - insets.top;
        tablero.moverFicha(new MouseEvent(evt.getComponent(), evt.getID(), evt.getWhen(), evt.getModifiersEx(), adjustedX, adjustedY, evt.getClickCount(), evt.isPopupTrigger()));

    }

    public void arrastrarFicha(MouseEvent evt) {

        Insets insets = this.getInsets();
        int adjustedX = evt.getX() - insets.left;
        int adjustedY = evt.getY() - insets.top;
        tablero.arrastrarFicha(new MouseEvent(evt.getComponent(), evt.getID(), evt.getWhen(), evt.getModifiersEx(), adjustedX, adjustedY, evt.getClickCount(), evt.isPopupTrigger()));

    }

    public void realizaMovimiento(MouseEvent evt) {

        Insets insets = this.getInsets();
        int adjustedX = evt.getX() - insets.left;
        int adjustedY = evt.getY() - insets.top;

        int valida = validaHitbox(new MouseEvent(evt.getComponent(), evt.getID(), evt.getWhen(), evt.getModifiersEx(), adjustedX, adjustedY, evt.getClickCount(), evt.isPopupTrigger()));
        if (valida == 0) {

            return;
        }
        if (!presentador.isTurno()) {
            tablero.resetearFichaSeleccionada();
            return;
        }
        FichaDTO ficha = tablero.obtenerFichaSeleccionada();
        FichaTableroDTO f = new FichaTableroDTO(ficha.getImagen(), ficha.getPuntoAbajo(), ficha.getPuntoArriba());

        presentador.realizaMovimiento(f, valida);
//        boolean validaFicha = false;
//
//        switch (valida) {
//            case 1:
//                validaFicha = presentador.realizaMovimiento(f, valida);
//                break;
//            case 2:
//                validaFicha = presentador.realizaMovimiento(f, valida);
//                break;
//            case 3:
//                validaFicha = presentador.realizaMovimiento(f, valida);
//                break;
//        }
//        if (!validaFicha) {
//            tablero.resetearFichaSeleccionada();
//        }
//        if (validaFicha) {
//            switch (valida) {
//                case 1:
//                    tablero.colocarInicial(f);
//                    break;
//                case 2:
//                    tablero.colocarTrenDerecha(f);
//                    break;
//                case 3:
//                    tablero.colocarTrenIzquierda(f);
//                    break;
//            }
////            presentador.eliminarFichaJugador(ficha);
//        }
    }

    public void regresaFicha() {
        tablero.resetearFichaSeleccionada();
    }

    public void colocarFicha(FichaTableroDTO f, int zona) {

        switch (zona) {
            case 1:
                System.out.println("inicial");
                tablero.colocarInicial(f);
                break;
            case 2:
                System.out.println("derecha");
                tablero.colocarTrenDerecha(f);
                break;
            case 3:
                System.out.println("izquierda");
                tablero.colocarTrenIzquierda(f);
                break;
        }
    }

    public void iniciarJuego() {
        tablero.setLayout(null);
//        tablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Jugador1.setVisible(false);
        Jugador2.setVisible(false);
        Jugador3.setVisible(false);
        Jugador4.setVisible(false);

        add(tablero);
//        presentador.iniciarPartida();
        this.partidaIniciada = true;

        this.setContentPane(tablero);

//        tablero.setLayout(null);
        this.remove(btnRobar);

        this.remove(btnPasarTurno);
        this.remove(btnTerminar);
        this.remove(Votacion);
        btnRobar.setVisible(true);

        btnPasarTurno.setVisible(true);
//        btnPasarTurno.setBounds(5, 5, 100, 30);
        btnTerminar.setVisible(true);
//        btnTerminar.setBounds(150, 5, 200, 30);
//        Rectangle s = Votacion.getBounds();
//        Rectangle s1 = btnPasarTurno.getBounds();
//        Rectangle s2 = btnTerminar.getBounds();
//        Rectangle s3 = btnRobar.getBounds();

        tablero.add(Votacion, new AbsoluteConstraints(Votacion.getX(), Votacion.getY(), Votacion.getWidth(), Votacion.getHeight()));
        tablero.add(btnPasarTurno, new AbsoluteConstraints(btnPasarTurno.getX(), btnPasarTurno.getY(), btnPasarTurno.getWidth(), btnPasarTurno.getHeight()));
        tablero.add(btnTerminar, new AbsoluteConstraints(btnTerminar.getX(), btnTerminar.getY(), btnTerminar.getWidth(), btnTerminar.getHeight()));
        tablero.add(btnRobar, new AbsoluteConstraints(btnRobar.getX(), btnRobar.getY(), btnRobar.getWidth(), btnRobar.getHeight()));
        btnPasarTurno.setVisible(true);
        btnTerminar.setVisible(true);
//        Votacion.setBounds(s);
        btnPasarTurno.setBounds(300, 40, 130, 30);
//        btnTerminar.setBounds(s2);
        btnRobar.setBounds(440, 40, 130, 30);
        btnTerminar.setBounds(580, 40, 220, 30);
        Votacion.setVisible(false);
        Votacion.setBounds(440, 250, 500, 232);
//        tablero.repaint();
//        tablero.agregarFichasIniciales();
    }

    public void votacion() {
        votar = true;
        btnIniciarVotacion.setVisible(false);
        btnAbandonarPartida.setVisible(false);
        Jugador1.setVisible(false);
        Jugador2.setVisible(false);
        Jugador3.setVisible(false);
        Jugador4.setVisible(false);
        Votacion.setVisible(true);
        BtnNo.setEnabled(true);
        btnSi.setEnabled(true);
        if (partidaIniciada) {
            Votacion.setBounds(400, 190, 530, 230);
            
            lblVotacion.setIcon(new ImageIcon(getClass().getResource("/Grafico/Botones/Terminar.png")));
        }else{
            Votacion.setBounds(200, 200, 530, 230);
        }
        
    }

    public void votacionNoaceptada() {
        Votacion.setVisible(false);
        btnIniciarVotacion.setVisible(true);
        btnAbandonarPartida.setVisible(true);
        Jugador1.setVisible(true);
        Jugador2.setVisible(true);
        Jugador3.setVisible(true);
        Jugador4.setVisible(true);
        btnSi.setEnabled(true);
        BtnNo.setEnabled(true);
    }

    public void respuestaVotacion() {
        presentador.respuestaVotacion(respuesta);
        BtnNo.setEnabled(false);
        btnSi.setEnabled(false);
    }

    public void activarBotones() {
        BtnNo.setEnabled(true);
        btnSi.setEnabled(true);
    }

    public void mostrarMensaje() {
        JOptionPane.showMessageDialog(this, "Faltas jugadores");
    }

    public void inicioVotacion() {
        presentador.iniciarVotacion();
    }

    public void iniciarVotacionTerminarPartida() {
        presentador.iniciarVotacionTerminarPartida();
    }

    public boolean isTurno() {
        return presentador.isTurno();
    }

    public void asignarJugadorJugando(JugadorDTO jugador) {
        tablero.setJugador(jugador);
        this.pintarFichas();

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNo;
    private javax.swing.JPanel Jugador1;
    private javax.swing.JPanel Jugador2;
    private javax.swing.JPanel Jugador3;
    private javax.swing.JPanel Jugador4;
    private javax.swing.JPanel JugadorPuntacion1;
    private javax.swing.JPanel JugadorPuntacion2;
    private javax.swing.JPanel JugadorPuntacion3;
    private javax.swing.JPanel JugadorPuntacion4;
    private javax.swing.JPanel Votacion;
    private javax.swing.JButton btnAbandonarPartida;
    private javax.swing.JButton btnIniciarVotacion;
    private javax.swing.JButton btnPasarTurno;
    private javax.swing.JButton btnRobar;
    private javax.swing.JButton btnSi;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblAvatar1;
    private javax.swing.JLabel lblAvatar2;
    private javax.swing.JLabel lblAvatar3;
    private javax.swing.JLabel lblAvatar4;
    private javax.swing.JLabel lblAvatarP1;
    private javax.swing.JLabel lblAvatarP2;
    private javax.swing.JLabel lblAvatarP3;
    private javax.swing.JLabel lblAvatarP4;
    private javax.swing.JLabel lblCoronitaBroce;
    private javax.swing.JLabel lblCoronitaDorada;
    private javax.swing.JLabel lblCoronitaPlateada;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JLabel lblJugador3;
    private javax.swing.JLabel lblJugador4;
    private javax.swing.JLabel lblJugadorP1;
    private javax.swing.JLabel lblJugadorP2;
    private javax.swing.JLabel lblJugadorP3;
    private javax.swing.JLabel lblJugadorP4;
    private javax.swing.JLabel lblPuntosP1;
    private javax.swing.JLabel lblPuntosP2;
    private javax.swing.JLabel lblPuntosP3;
    private javax.swing.JLabel lblPuntosP4;
    private javax.swing.JLabel lblVotacion;
    private javax.swing.JLabel panel1;
    private javax.swing.JLabel panel2;
    private javax.swing.JLabel panel3;
    private javax.swing.JLabel panel4;
    private javax.swing.JPanel pantallaPuntuaciones;
    private javax.swing.JPanel pantallaespera;
    // End of variables declaration//GEN-END:variables

}
